apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    role: backend
    app: bc_26
spec:
  # type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
      # nodePort: 30010
  selector:
    role: backend
    app: bc_26
