apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    role: frontend
    app: bc_26
spec:
  # type: NodePort
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 30009
  selector:
    role: frontend
    app: bc_26
