apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: bc-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bc-frontend
  template:
    metadata:
      labels:
        app: bc-frontend
    spec:
      containers:
        - name: bc-frontend
          image: gnvsai2020/bcimage4
          env:
            - name: baseURL
              value: http://ac2c67c4393164646be143185bcbca50-687694456.us-east-2.elb.amazonaws.com:8090
          ports:
            - containerPort: 80
