apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: 
    name: react-app
    app: react-app

spec: 
  template: 
    metadata:
      name: react-pod
      labels: 
        name: react-app
        app: react-app
    spec:
      containers:
        - name: react-app
          image: {{ .Values.image.repository }} 
          ports:
            - containerPort: 3000

  replicas: {{ .Values.replicaCount }}
  
  selector: 
    matchLabels:
      name: react-app
      app: react-app