apiVersion: v1 
kind: Service
metadata: 
  name: {{ .Release.Name }}
  
  labels: 
    name: react-service
    app: react-app
    org: {{ .Values.orgLabel }}

spec: 
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: {{ .Values.service.nodePort }}
  selector: 
    name: react-app
    app: react-app